//
//  EmailTextField.swift
//  SocialVUE
//
//  Created by Parth Adroja on 3/27/16.
//  Copyright (c) 2016 Mastermind. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class EmailTextField : NSObject {

    //// Cache

    private struct Cache {
        static let color: UIColor = UIColor(red: 0.961, green: 0.965, blue: 0.969, alpha: 1.000)
    }

    //// Colors

    public class var color: UIColor { return Cache.color }

    //// Drawing Methods

    public class func drawCanvas1() {

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(roundedRect: CGRectMake(0.5, 0.5, 287, 50), byRoundingCorners: [UIRectCorner.TopLeft, UIRectCorner.TopRight], cornerRadii: CGSizeMake(8, 8))
        rectanglePath.closePath()
        EmailTextField.color.setFill()
        rectanglePath.fill()
        UIColor.lightGrayColor().setStroke()
        rectanglePath.lineWidth = 1
        rectanglePath.stroke()
    }
    public class func drawCanvas2() {
        
        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(roundedRect: CGRectMake(0.5, 0.5, 287, 48), byRoundingCorners: [UIRectCorner.BottomLeft, UIRectCorner.BottomRight], cornerRadii: CGSizeMake(8, 8))
        rectanglePath.closePath()
        EmailTextField.color.setFill()
        rectanglePath.fill()
        UIColor.lightGrayColor().setStroke()
        rectanglePath.lineWidth = 1
        rectanglePath.stroke()
    }

}
